site_name: CitCom<sup>AI</sup> Hub
site_url: https://citcomai-hub.github.io
repo_url: https://github.com/CitComAI-Hub/CitComAI-Hub.github.io
edit_uri: edit/main/docs/
repo_name: CitComAI-Hub/CitComAI-Hub.github.io
copyright: Copyright &copy; 2023 - 2024 CitCom.ai Hub
site_dir: public
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - assets/css/data_catalog.css
extra_javascript:
  - assets/js/data_catalog.js
theme:
  custom_dir: docs/overrides
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - content.action.edit
    - navigation.sections
    - navigation.footer
    - navigation.indexes
  palette:
    primary: black
nav:
  - welcome.md
  - Getting started:
      - getting_started/index.md
      - Nodes & Countries: getting_started/nodes_countries.md
      - Interoperability: getting_started/interoperability.md
      - Data spaces:
          - getting_started/data_spaces/index.md
          - Join one: getting_started/data_spaces/join.md
          - Deploy one: getting_started/data_spaces/deployment.md
      - Get involved: getting_started/get_involved.md
  - Data catalog:
      - data_catalog/index.md
      - data_catalog/instructions.md
  - Guides:
      - documentation/index.md
      - Data Federation:
          - documentation/data_federation/index.md
          # - NGSI-LD to NGSI-LD:
          #   - documentation/data_federation/ngsild_to_ld/index.md
          - NGSI-v2 to NGSI-LD:
              # - documentation/data_federation/ngsiv2_to_ld/index.md
              - Lepus: documentation/data_federation/ngsiv2_to_ld/lepus.md
              - FIWARE IoT-Agent: documentation/data_federation/ngsiv2_to_ld/iot_agent.md
        # - Custom brokers:
        #   - documentation/data_federation/custom/index.md
      - Data Space Connectors:
          - documentation/data_space_connectors/index.md
          - Eclipse: documentation/data_space_connectors/eclipse_mvd.md
          - Fiware:
              - documentation/data_space_connectors/fiware/index.md
              - Legacy (v. 1.X.X):
                  - documentation/data_space_connectors/fiware/legacy_1.X.X/index.md
                  - Deployments:
                      - AWS deployment: documentation/data_space_connectors/fiware/legacy_1.X.X/deployments/aws_deployment.md
                      - Local deployment: documentation/data_space_connectors/fiware/legacy_1.X.X/deployments/local_deployment.md
                      - Minimum Viable Data Space Infrastructure (MVDS-IaaS):
                          - documentation/data_space_connectors/fiware/legacy_1.X.X/deployments/mvds_iaas/index.md
              # - Latest (v. 2.X.X):
              #     - documentation/data_space_connectors/fiware/latest_2.X.X/index.md
  - AI services:
      - services/index.md
      - Minimal Interoperable AI Service: services/waste_collection.md
      - Container Location Optimization: services/wastecontainer_location_optimization.md
  - TEF Nodes:
      - tef/index.md
      - Nordic - POWER: 
        - tef/nordic_power/doll_living_lab.md
        - tef/nordic_power/aarhus_city_lab.md
        - tef/nordic_power/net_zero_innovation_hub.md
        - tef/nordic_power/dti.md
        - tef/nordic_power/center_denmark.md
        - tef/nordic_power/gate21.md
        - tef/nordic_power/rise.md
        - tef/nordic_power/tampere.md
      - Central - MOVE:
        - tef/central_move/mechelen.md
        - tef/central_move/brussels.md
        - tef/central_move/eindhoven.md
        - tef/central_move/paris.md
        - tef/central_move/list.md
      - South - CONNECT:
        - tef/south_connect/valencia.md
        - tef/south_connect/milano.md
        - tef/south_connect/warsaw.md
  - Toolbox:
      - toolbox/index.md
      - AI Toolkit: toolbox/ai_toolkit.md
      - MIMs Toolkit: toolbox/mims_toolkit.md
      - Other Tools: toolbox/other_toolkit.md
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - neoteroi.timeline
plugins:
  - git-authors:
      show_email_address: false
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - macros
extra:
  generator: false
  labels:
    data_brokers: 
      fiware: '<span style="background-color:green; color:white; padding:2px 4px; border-radius:4px;">Fiware</span>'
      kafka: '<span style="background-color:black; color:white; padding:2px 4px; border-radius:4px;">Kafka</span>'
      iot_ticket: '<span style="background-color:blue; color:white; padding:2px 4px; border-radius:4px;">IoT-Ticket Azure</span>'
    api_brokers:
      ngsi_v2: '<span style="background-color:orange; color:white; padding:2px 4px; border-radius:4px;">NGSI-v2</span>'
      ngsi_ld: '<span style="background-color:green; color:white; padding:2px 4px; border-radius:4px;">NGSI-LD</span>'
      custom: '<span style="background-color:red; color:white; padding:2px 4px; border-radius:4px;">Custom</span>'
    ds4ssc_compliant:
      yes_comp:
        data_sources: '<span style="background-color:rgb(51,255,51); color:black; padding:2px 4px; border-radius:4px; border:1px solid black;"><strong>Data Sources</strong></span>'
        data_broker: '<span style="background-color:red; color:white; padding:2px 4px; border-radius:4px; border:1px solid black;"><strong>Data Broker</strong></span>'
        data_api: '<span style="background-color:rgb(255,51,255); color:white; padding:2px 4px; border-radius:4px; border:1px solid black;"><strong>Data API</strong></span>'
        data_idm_auth: '<span style="background-color:orange; color:white; padding:2px 4px; border-radius:4px; border:1px solid black;"><strong>IdM & Auth</strong></span>'
        data_publication: '<span style="background-color:rgb(204,255,255); color:black; padding:2px 4px; border-radius:4px; border:1px solid black;"><strong>Data Publication</strong></span>'
      no_comp:
        data_sources: '<span style="background-color:rgba(51,255,51,0.2); color:gray; padding:2px 4px; border-radius:4px;">Data Sources</span>'
        data_broker: '<span style="background-color:rgba(255,0,0,0.2); color:gray; padding:2px 4px; border-radius:4px;">Data Broker</span>'
        data_api: '<span style="background-color:rgba(255,51,255,0.2); color:gray; padding:2px 4px; border-radius:4px;">Data API</span>'
        data_idm_auth: '<span style="background-color:rgba(255,165,0,0.2); color:gray; padding:2px 4px; border-radius:4px;">IdM & Auth</span>'
        data_publication: '<span style="background-color:rgba(204,255,255,0.2); color:gray; padding:2px 4px; border-radius:4px;">Data Publication</span>'
