metadata:
  DATASET-NAME:
    table_column: "Dataset"
  SUPER-NODE:
    table_column: "Super Node"
  TEF-NODE:
    table_column: "TEF Node"
  SITE:
    table_column: "Site"
  DATA-MODEL:
    table_column: "Data Model"
  SAMPLIG-TIME:
    table_column: "Sampling Time"
  HISTORICAL:
    table_column: "Historical"
  OWNER:
    table_column: "Owner"
  GET-ACCESS:
    table_column: "Get Access"

dataset:
  - ATTRIBUTE
  - TYPE
  - UNITS (SI)
  - DESCRIPTION/COMMENTS

markdowns:
  index: "docs/data_catalog/index.md"
  dataset_details: "docs/data_catalog/metadata_datasets"

github_actions:
  csv_path: "/tmp/csv_files"
